<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<UseRidGraph>true</UseRidGraph>
		<LangVersion>11</LangVersion>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<Nullable>disable</Nullable>
        <OutputPath>..\FuseCP.Server\bin\DNS\</OutputPath>
    </PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugType>full</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\VersionInfo.cs" Link="VersionInfo.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.Management" Version="10.0.8" />
		<PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
		<PackageReference Include="System.Management.Automation" Version="7.6.2" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\FuseCP.Providers.Base\FuseCP.Providers.Base.csproj" />
		<ProjectReference Include="..\FuseCP.Server.Utils\FuseCP.Server.Utils.csproj" />
	</ItemGroup>
</Project>
