<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>13</LangVersion>
        <IsPackable>false</IsPackable>
        <TestTfmsInParallel>false</TestTfmsInParallel>
        <UseRidGraph Condition="'$(TargetFramework)' == 'net10.0'">true</UseRidGraph>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="app.config" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="app.config">
            <SubType>Designer</SubType>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EntityFramework" Version="6.5.1" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
        <PackageReference Include="Azure.Identity" />
        <PackageReference Include="System.Linq.Dynamic.Core" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="MSTest.TestAdapter" />
        <PackageReference Include="MSTest.TestFramework" />
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FuseCP.EnterpriseServer.Base\FuseCP.EnterpriseServer.Base.csproj" />
        <ProjectReference Include="..\FuseCP.EnterpriseServer.Code\FuseCP.EnterpriseServer.Code.csproj" />
        <ProjectReference Include="..\FuseCP.EnterpriseServer.Data\FuseCP.EnterpriseServer.Data.csproj" />
        <ProjectReference Include="..\FuseCP.EnterpriseServer\WebServices\FuseCP.Build\FuseCP.EnterpriseServer.Client.csproj" />
        <ProjectReference Include="..\FuseCP.Server.Utils\FuseCP.Server.Utils.csproj" />
        <ProjectReference Include="..\FuseCP.Tests\FuseCP.Tests.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="App_Data\" />
        <Folder Include="TestResults\" />
    </ItemGroup>

</Project>


